= Charity chess games

== Description

=== Данный проект задуман для проведения благотворительных партий по шахматам в формате один против многих.

Пользователи регистрируются в системе. Некий размер баланса на счёте пользователя даёт возможность получить ему статус VIP. Пользователь со статусом VIP имеет возможность стать инициатором благотворительной шахматной партии регистрируя её с некой ставкой. Остальные пользователи могут стать участниками этой партии подключаясь к ней со ставкой не меньшей минимальной.

Проведение партии в данном проекте не реализовывается. А результат партии определит Random.

Ход партии:

* Первый ход совершает сторона, которую определяет VIP пользователь (в данном примере рассмотрим первый ход VIP пользователя, противостоят ему группа пользователей подключившихся к ней).
* Каждый пользователь группы совершает ход, который регистрируется в таблице ходов пользователей. Из таблицы ходов выбирается тот, который пользователи совершили чаще. В ситуации когда несколько ходов в таблице имеют одинаковое количество совершения пользователями, всем пользователям предлагается выбрать один из имеющих одинаковое совершение. (Возможно применение не второго этапа голосования, а сравнение суммарного рейтинга пользователей проголосовавших за ходы имеющие одинаковое положение в таблице ходов).
* После совершения хода одной из сторон все пользователи получают уведомления о его совершении. Спорные ситуации связанные с ходом пользователей также являются ситуацией в которой пользователи получают уведомления и возможные решения этой ситуации (в варианте с вторым этапом голосования).

Результатом партии является выигрыш одной из сторон или ничья.
В зависимости от результата суммарный объём всех ставок делится в процентном соотношении:

* 70% благотворительный фонд. Адресата фонда определяет VIP пользователь организовавший данную партию в момент создания партии.
* 5% организаторам данных благотворительных партий. (Поддержание и развитие проекта, реклама предстоящих игр)
* 25% победителю партии. В случае победы группы пользователей 25% от объёма всех ставок делится в процентном соотношении в зависимости от ставки конкретного пользователя к общей сумме ставок всех пользователей данной группы.

Возможно другое процентное соотношение и количество пунктов разделения выигрышного фонда.

==== Какую проблему данный проект решает или что нового приносит для пользователей?

* Проект помогает осветить проблему нуждающуюся в благотворительности (COVID, онкология, помощь детям, помощь пострадавшим от стихийного бедствия и т.д)
* Шахматы — это бесконечные упражнения для ума, который развивают умственные способности, используемые на протяжении всей жизни, такие как: концентрация, критическое мышление, абстрактное мышление, решение проблем, распознавания образов, стратегическое планирование, память, творчество, анализ, синтез и оценка.
* Проект даёт возможность сразиться в шахматы со своим кумиром.
* Проект не позволяет пользователям выводить средства на личные счета. Все средства в системе можно использовать только в благотворительных целях.

==== Потенциальные пользователи

* Публичные, известные люди занимающиеся благотворительностью, которые хотят привлечь внимание к волнующей их проблеме.
* Люди которым интересны шахматы.
* Люди которым интересна благотворительность.
* Люди желающие сразится со своими кумирами или просто известными людьми.

==== Аналогичные приложения

* Проводятся https://chesshouse.by/tournaments/festival-18-04-2020[онлайн турниры] и https://www.legalchess.ru/[офлайн турниры].

==== Конкурентное преимущество

* Турниры проводятся в онлайн режиме, что актуально в условиях пандемии.
* Не нужно регистрироваться на одном ресурсе, а платить вступительные взносы через другую систему.
* Игры проводятся в другом формате нежели турниры приведенные выше, что позволяет пользователям играть против особой известной личности.
* Партии проводится в формате "игра по переписке", что не привязывает всех участвующих людей к постоянному ожиданию хода соперника. Временное ограничение на осуществление своего хода имеет порог и имеет возможность заранее проинформировать участников о скором его наступлении.