= Charity chess games

== Description

=== This project is designed to hold charity chess games in a format of one against many.

Users are registered on the system. A certain amount of balance on the user’s account gives the user the opportunity to receive the VIP status. A user with VIP status has the opportunity to become the initiator of a charity chess game by registering it with a certain rate. Other users can join this group. They will join at a minimum rate or higher.

The progress of the game is not realized in this project. The result of the game will be determined by accident.

Course of the game:

* First move is made by the party defined by the VIP user (in this example, consider the first move of a VIP user, opposed by a group of users connected to the game)
* Each user of the group makes a move, which is recorded in the user moves table. The move table selects the move that users made more frequently. In a situation where several moves in a table are selected by users the same number of times, all users are asked to choose one of these moves. (It is possible to use not the second round of voting, but a comparison of the total rating of users who voted for the moves that lead in the table of moves).
* Once a move has been made by one of the parties, all users are notified. Controversy over the course of the game is also a situation where users receive notifications and possible solutions (in the case of the second ballot).

The result of a party is a win or draw.
Depending on the result, the total amount of all bets is divided in percentage ratio:

* 70% of the charity. The fund’s addressee is identified by the VIP user when the game is created.
* 5% of charity event organizers. (Project support and development, promotion of upcoming games).
* 25% to the winner of the party. If a group of users wins, 25% of all bets are divided in percentage terms, depending on the bet of a particular user, to the total bet of all users of a given group.

The number of items and the percentage for each item may vary.

==== What problems does the project solve or what innovations for users?

* The project helps to voice the problem of charity (COVID, oncology, helping children, disaster relief, etc.)
* Chess is an endless exercise for the mind that develops the mental abilities that are used throughout life, such as concentration, critical thinking, abstract thinking, problem-solving, pattern recognition, strategic planning, Memory, creativity, analysis, synthesis and evaluation.
* The project gives you an opportunity to fight in chess with your idol.
* The project does not allow users to transfer funds to personal accounts. All funds in the system can be used only for charitable purposes.

==== Potential users

* Public, well-known people who want to draw attention to the problems of charity.
* People who are interested in chess.
* People who are interested in charity.
* People who want to fight their idols or famous people.

==== Similar annexes

https://chesshouse.by/tournaments/festival-18-04-2020[Online] and https://www.legalchess.ru/[offline] tournaments

==== Competitive advantage

* Tournaments are held online, which is relevant in the context of a pandemic.
* User registration and financial transactions in one application
* Games are held in a different format than the tournaments mentioned above, which allows users to play against a special person.
* The game is held in the format of "Correspondence Game", which does not bind all participating people to the constant wait of the opponent’s move. The temporary restriction on the exercise of its movement has a threshold, and it is possible to inform the participants in advance of its imminent occurrence.

==== Business analysis

User stories

https://miro.com/welcomeonboard/dVg4TVZDc2Z6SVJIeEtVcEUzRUR1dUxjWmtpRjhkN3hLTzJnOXZxQjdkSlJmblMzOUN2UFJ1aXk1RThvNFdPRXwzNDU4NzY0NTE2ODY1NjM1MDgx?invite_link_id=73846758994[Mind Map]

UML class diagram

https://app.dbdesigner.net/designer/schema/492337[UML Class Diagram with dbdesigner]